name = "yukios-remote-signaling"
main = "signaling-worker.js"
compatibility_date = "2026-07-29"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "Room"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]
