export const AppSource = {
  COMMAND_PALETTE: "CommandPalette",
  CLIPBOARD_MANAGER: "Clipboard Manager",
  EXPLORER: "Explorer",
  YUKI_CONVERT: "Yuki Convert",
  SETUP: "Setup",
  INSTALLED_APPS: "Installed Apps",
  ARCHIVE_EXTRACTOR: "Archive Extractor",
  SETTINGS: "Settings",
  NOTEPAD: "Notepad",
  TERMINAL: "Terminal",
  BROWSER: "Browser",
  CALCULATOR: "Calculator",
  CALENDAR: "Calendar",
  CAMERA: "Camera",
  MARKDOWN: "Markdown",
  OFFICE: "Office",
  DATA_EDITOR: "Data Editor",
  TASK_MANAGER: "Task Manager",
  ACHIEVEMENTS: "Achievements",
  ABOUT: "About",
  NEWS: "News",
  WEATHER: "Weather",
  CATEGORIES: "Categories",
  PROFILE_CUSTOMIZER: "Profile Customizer",
  SHORTCUTS: "Shortcuts",
  APP_CREATOR: "App Creator",
  YUKI_OS_GUIDE: "sitalOS Guide",
  AI_ASSISTANT: "Yuki AI",
  BRIGHTNESS: "Brightness",
  EMOJI_SELECTOR: "Emoji Selector",
  SYSTEM: "System",
  RHYTHMS: "Rhythms",
  TORRENT_CLIENT: "Torrent Client",
  CLOCK: "Clock",
  CALENDAR_APP: "Calendar",
  WALLPAPER_ENGINE: "Wallpaper Engine"
};
