allowBuilds:
  "@mercuryworkshop/scramjet": false
  bufferutil: true
  canvas: false
  core-js: true
  electron: true
  esbuild: true
  ip-set: true
  node-datachannel: true
  sharp: true
  utf-8-validate: true
  utp-native: true
